In [1]:
import numpy as np

(math-lab-detinv)=
# Определитель матрицы. Обратная матрица

## Определитель матрицы

Определитель матрицы первого порядка равен единственному элементу этой матрицы.

In [2]:
A = np.array([[5]])
np.linalg.det(A)

np.float64(4.999999999999999)

Определитель квадратной матрицы размерностью $\left( 2 \times 2 \right)$:

$$ \begin{vmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{vmatrix} = a_{11} \cdot a_{22} - a_{12} \cdot a_{21}. $$

In [3]:
A = np.array([[1, 2], [-3, -4]])
A

array([[ 1,  2],
       [-3, -4]])

In [4]:
np.linalg.det(A)

np.float64(2.0000000000000004)

При нахождении определителя матрицы размерностью $\left( 3 \times 3 \right)$ необходимо "раскрыть" определитель по любой строке или столбцу с учетом матрицы знаков:

$$ \begin{vmatrix} a_{11} & a_{12} & a_{13} \\ a_{21} & a_{22} & a_{23} \\ a_{31} & a_{32} & a_{33} \end{vmatrix} = a_{11} \cdot \begin{vmatrix} a_{22} & a_{23} \\ a_{32} & a_{33} \end{vmatrix} - a_{12} \cdot \begin{vmatrix} a_{21} & a_{23} \\ a_{31} & a_{33} \end{vmatrix} + a_{13} \cdot \begin{vmatrix} a_{21} & a_{22} \\ a_{31} & a_{32} \end{vmatrix}. $$

In [5]:
A = np.array([[1, 3, 14], [5, 2, -7], [4, -2, 7]])
np.linalg.det(A)

np.float64(-441.0)

Одним из свойств векторов является то, что если определитель матрицы, составленной из координат этих векторов, равен нулю, то данные векторы являются [коллинеарными](LAB-2-VectorOperations.md#math-lab-vectoroperations-collinearity). Рассмотрим пример. Пусть даны два вектора $\mathbf{v_1} = \begin{bmatrix} 1 \\ 3 \end{bmatrix}$ и $\mathbf{v_2} = \begin{bmatrix} 2 \\ 6 \end{bmatrix}$. Тогда матрица $\mathbf{M} = \begin{bmatrix} 1 & 2 \\ 3 & 6 \end{bmatrix}$. Вычислим определитель этой матрицы:

In [6]:
M = np.array([[1, 2], [3, 6]])
np.linalg.det(M)

np.float64(-3.330669073875464e-16)

Определитель этой матрицы равен нулю, следовательно, векторы $\mathbf{v_1}$ и $\mathbf{v_2}$ являются коллинеарными.

## Обратная матрица

```{admonition} Определение
:class: tip
Под ***обратной матрицей*** матрице $\mathbf{M}$ называется матрица, удовлетворяющая следующему выражению:

$$ \mathbf{M} \mathbf{M}^{-1} = \mathbf{E}, $$

где $\mathbf{E}$ – единичная матрица.
```

При умножении матрицы на единичную матрицу в результате получается исходная матрица.

In [7]:
A = np.array([[1, 2], [-1, 3]])
E = np.array([[1, 0], [0, 1]])
A.dot(E)

array([[ 1,  2],
       [-1,  3]])

При нахождении обратной матрицы можно использовать следующее выражение:

$$ \mathbf{M}^{-1} = \frac{1}{\left| \mathbf{M} \right|} \cdot \mathbf{M}_{*}^\top, $$

где $\mathbf{M}_{*}^\top$ – транспонированная матрица алгебраических дополнений. Следует отметить, что, исходя из указанного выше выражения, необходимым условием для существования обратной матрицы является $\left| \mathbf{M} \right| \neq 0$.

Однако использование библиотеки [*numpy*](https://numpy.org/) может значительно упростить данную операцию.

In [8]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.6, -0.4],
       [ 0.2,  0.2]])

In [9]:
A.dot(A_inv)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

Матрица, обратная обратной матрице $\mathbf{A}$, равняется самой матрице $\mathbf{A}$:

In [10]:
np.linalg.inv(np.linalg.inv(A))

array([[ 1.,  2.],
       [-1.,  3.]])